### PR TITLE
New Setting to Omit Non-Standard Port Numbers During Link Checking

### PR DESCRIPTION
**Pull request by bmsapp**
Hi Dan, 

Sorry for the multiple commits. I am not tooled for Git on this computer (and not that skilled with Git yet) so I used the github UI to do all of the changes. 

I tried to implement this new setting using your current configuration scheme with config.js. This caused me to have to pass it through multiple layers but I would rather do that than to introduce numerous ways to configure LinkChecker.

Thanks, 

Ben

### CODE REVIEW

**Comment by bmsapp** [comment]
I made a mistake in my param comment for allowNonStandardPortInBaseUri

Sorry it should read something like:

If **false**, when checking links found in a document, a non-standard port **will** be omitted from the request.

**Comment by DanDiplo** [comment]
Thanks, Ben, I'll test this today and if all OK (which I'm sure it will be) I'll release a new package. Thanks for your help!

**Comment by DanDiplo** [comment]
I've given it the once-over and all looks OK. Good work! Still works as before with default config, but changing `omitPortDuringChecks` to `true` works.

I appreciate using JS for config creates quite a lot of layers, but the idea was that the config also can be configured from the UI in the linchecker. In this case, didn't seem worth adding an option to make it togglable from the interface as it is what I'd see as an "advanced option" for those that need it.

New package with your contribution released: https://our.umbraco.org/projects/backoffice-extensions/diplo-link-checker/

**Comment by bmsapp** [comment]
Awesome! Thanks again.

**Pull request merged**
