### PR TITLE
Update with additional options

### PR DESCRIPTION
**Pull request by hfloyd**
Updated with settings to "Check internal links only" and Display only errors of certain codes (default = 300,400,500)

### CODE REVIEW

**Comment by DanDiplo** [comment]
Hi Heather,

Thanks so much for this. I'm currently a bit under the weather, but I'll look at your PR as soon as I get time.

Cheers,

Dan

**Comment by hfloyd** [comment]
Thanks, @DanDiplo , Take your time - I hope you're feeling better soon!

**Comment by DanDiplo** [comment]
Changes all look good! This has been one of my most neglected projects and I've been looking to rewrite some of it to be more efficient. So when I do that I'll incorporate your changes and release a new version. I'll also hopefully add a NuGet version, too. Thanks again for your contribution!

**Comment by hfloyd** [comment]
Thanks, @DanDiplo I was happy to contribute. :-)

**Pull request merged**
